version: '3.4'

services:

  # Key cloak...
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port=8180"]
    ports:
      - 8180:8180

    networks:
      - workbench

  
  droolswb:
    image: droolswb:latest
    
    depends_on:
      - keycloak
    ports:
      - 8080:8080
      - 9990:9990
    networks:
      - workbench

networks:
  workbench:
  

